name: Dastardly Scan

on:
  push:
    branches:
      - main

jobs:
  dastardly-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dastardly Scan Action
        uses: PortSwigger/dastardly-github-action@f72f38f8b4ac8ed59c69854cc77eb9d53e50e78b
        with:
          target-url: https://orangetech-ten.vercel.app/
